from __future__ import annotations

import json

from korean_social_simulator.models import SimulationEvent

_LIMITATIONS_TEXT = (
    "This is a synthetic simulation. Results are NOT real-world predictions. "
    "All participants are synthetic personas generated by Nemotron-Personas-Korea. "
    "This report should be used for hypothesis generation and risk analysis only, "
    "not as evidence of real-world behavior. External validation is required before "
    "making decisions based on these results."
)

_FOLLOW_UP_VALIDATION_TEXT = (
    "Recommended: Validate findings through real-user studies, expert review, or "
    "A/B testing before making product decisions."
)


def render_report(
    run_id: str,
    status: str,
    metrics: dict[str, str | int | float | None],
    events: list[SimulationEvent],
    scenario_title: str = "",
    scenario_hypothesis: str = "",
    safety_notes: list[str] | None = None,
    errors: list[str] | None = None,
    warnings: list[str] | None = None,
) -> str:
    """Render a simulation run as a markdown report.

    Args:
        run_id: Unique simulation run identifier.
        status: Final run status such as ``success``, ``partial``, or ``failed``.
        metrics: Aggregated metric values for the run.
        events: Ordered simulation events to summarize and sample.
        scenario_title: Optional scenario title shown in the summary.
        scenario_hypothesis: Optional scenario hypothesis shown in the summary.
        safety_notes: Optional safety notes associated with the run.
        errors: Optional run errors to surface in the report.
        warnings: Optional run warnings to surface in the report.

    Returns:
        A deterministic markdown report string for the provided simulation run.
    """
    normalized_safety_notes = safety_notes or []
    normalized_errors = errors or []
    normalized_warnings = warnings or []
    turn_count = max((event.turn for event in events), default=0)

    lines = [
        f"## Simulation Report: {run_id}",
        "",
        "## Summary",
        "",
        f"- run_id: {run_id}",
        f"- status: {status}",
        f"- scenario_title: {scenario_title or '(not provided)'}",
        f"- scenario_hypothesis: {scenario_hypothesis or '(not provided)'}",
        f"- event_count: {len(events)}",
        f"- turn_count: {turn_count}",
    ]

    if status in {"partial", "failed"}:
        lines.extend(
            [
                f"- warning_count: {len(normalized_warnings)}",
                f"- error_count: {len(normalized_errors)}",
                "- completion_note: This report reflects an incomplete simulation run. "
                "Review warnings and errors before interpreting results.",
            ]
        )

    lines.extend(
        [
            "",
            "## Metrics",
            "",
            "| metric_name | value |",
            "| --- | --- |",
        ]
    )

    if metrics:
        for metric_name, value in metrics.items():
            rendered_value = "N/A" if value is None else str(value)
            lines.append(f"| {metric_name} | {rendered_value} |")
    else:
        lines.append("| _none_ | _no metrics recorded_ |")

    lines.extend(["", "## Event Examples", ""])

    if events:
        for event in events[:3]:
            lines.extend(
                [
                    "```json",
                    json.dumps(
                        event.model_dump(),
                        ensure_ascii=False,
                        indent=2,
                        sort_keys=True,
                        default=str,
                    ),
                    "```",
                    "",
                ]
            )
        lines.pop()
    else:
        lines.append("No event examples available.")

    lines.extend(
        _render_bullet_section("Safety Notes", normalized_safety_notes, "No safety notes recorded.")
    )
    lines.extend(_render_bullet_section("Warnings", normalized_warnings, "No warnings recorded."))
    lines.extend(_render_bullet_section("Errors", normalized_errors, "No errors recorded."))
    lines.extend(
        [
            "## Limitations",
            "",
            _LIMITATIONS_TEXT,
            "",
            "## Follow-up Validation",
            "",
            _FOLLOW_UP_VALIDATION_TEXT,
        ]
    )

    return "\n".join(lines)


def _render_bullet_section(title: str, items: list[str], empty_message: str) -> list[str]:
    lines = ["", f"## {title}", ""]

    if items:
        lines.extend(f"- {item}" for item in items)
    else:
        lines.append(f"- {empty_message}")

    lines.append("")
    return lines
